version: "3.8"

services:

  openldap:
    image: osixia/openldap:1.5.0
    container_name: openldap
    hostname: ldap.example.com
    environment:
      - LDAP_ORGANISATION=Example Inc
      - LDAP_DOMAIN=example.com
      - LDAP_ADMIN_PASSWORD=admin
    ports:
      - "389:389"    # LDAP port
      - "636:636"
    volumes:
      - ./ldap/data:/var/lib/ldap
      - ./ldap/config:/etc/ldap/slapd.d
    restart: unless-stopped
    networks:
      - ldapnet

  # phpLDAPadmin UI (optional)
  phpldapadmin:
    image: osixia/phpldapadmin:0.9.0
    container_name: phpldapadmin
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=openldap
      - PHPLDAPADMIN_HTTPS=false
      - PHPLDAPADMIN_TRUST_PROXY_SSL=true
      - PHPLDAPADMIN_SERVER_ADMIN=admin@example.com
    ports:
      - "6443:80"
    depends_on:
      - openldap
    restart: unless-stopped
    networks:
      - ldapnet

  artemis_ldap:
    build: .
    container_name: artemis_ldap
    hostname: artemis_ldap
    ports:
      - "61618:61616"
      - "8162:8161"
      - "1011:1099"
      - "1101:1100"
    volumes:
      - ./broker:/opt/artemis/broker
    environment:
      - ARTEMIS_USERNAME=admin
      - ARTEMIS_PASSWORD=admin
    networks:
      - ldapnet
networks:
  ldapnet:
    driver: bridge